# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Aggiorna tutte le dipendenze npm/pnpm
  - package-ecosystem: "npm"
    directory: "/"            # radice repo: rileva package.json e pnpm-workspace.yaml
    schedule:
      interval: "weekly"      # controlla una volta a settimana
    open-pull-requests-limit: 10
    # (Facoltativo) raggruppa in una sola PR le patch di sicurezza
    groups:
      security:
        applies-to: security-updates
        dependency-type: "all"
  # Se hai workflow GitHub Actions da tenere aggiornati
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
