name: Bolt Preview Branch
on:
  push:
    branches: [ main ]
jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - run: pnpm install --frozen-lockfile
      - run: node tools/bolt-prune.js
      - run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git push --force origin HEAD:bolt-preview
